configfile:
  Windows: AppData
  Linux: ~/.config
logfile:
  Windows: C:\Logs\UtilityBelt\Profile\log.txt
  Linux: ~/.config
showtoolbar: true
profilepath:
  Windows: Users
  Linux: ~/.config/
expandedTree: True
scrollbar: True